name: notifications_programming
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1 
  sqflite: ^2.3.2 
  path: ^1.9.0
  intl: ^0.19.0
  flutter_native_splash: ^2.3.5
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    


flutter_native_splash:
  fullscreen: true
  color: "#B3E5FC"
  image: assets/splash.png
  android: true
  ios: true

